version: '3.8'

services:
  # PostgreSQL with pgvector and PostGIS
  postgres:
    image: pgvector/pgvector:pg16
    container_name: soosh-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soosh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and background tasks)
  redis:
    image: redis:7-alpine
    container_name: soosh-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama (optional - for local AI)
  # Uncomment if you want to run local AI instead of OpenAI
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: soosh-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  # ollama_data:
  #   driver: local
